version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "${USER_SERVICE_DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    environment:
      PORT: ${USER_SERVICE_PORT}
      DB_HOST: ${USER_SERVICE_DB_HOST}
      DB_PORT: ${USER_SERVICE_DB_PORT}
      DB_NAME: ${USER_SERVICE_DB_NAME}
      DB_USER: ${USER_SERVICE_DB_USER}
      DB_PASSWORD: ${USER_SERVICE_DB_PASSWORD}
    depends_on:
      - postgres
    networks:
      - app-network

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    environment:
      PORT: ${API_GATEWAY_PORT}
      USER_SERVICE_URL: http://user-service:${USER_SERVICE_PORT}
    depends_on:
      - user-service
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
